apiVersion: v1
kind: Service
metadata:
  name: devops-api
spec:
  selector:
    app: devops-api
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
spec:
  selector:
    matchLabels:
      app: devops-api
  replicas: 3
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api
        image: marcuskielman/devops_api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081