---
- name: API Environment Testing Setup
  hosts: localhost

  tasks:
    - name: Start Minikube
      shell: minikube start
    - name: Check for existing Pods and Replace
      shell: |
        kubectl get pods -o name | grep mariadb
      register: deployed
      ignore_errors: True
    - name: Replace API Pods
      shell: |
        kubectl replace -f ./kube_files/api_kube.yml
      when: deployed.stdout != ""
    - name: Set Up Kubernetes Deployment
      shell: |
        kubectl apply -f ./kube_files/api_maria_kube.yml
        kubectl get pods -o name | grep mariadb
      register: mariadb
      when: deployed.stdout == ""
    - name: Configure Database
      shell: |
        sleep 160s
        kubectl exec -i {{ mariadb.stdout_lines[4] }} -- mysql -uroot -proot classicmodels < mysqlsampledatabase.sql
      when: deployed.stdout == ""

